# Options: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  labels:
    - "Type: Chore"
  schedule:
    interval: daily
  target-branch: "dependabot-changes"
