name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Lint
        # Ignore `src/services` because `deno fmt` adds commas and `deno lint`
        # complains. Classic.
        run: deno lint --ignore=node_modules,.next,public,src/services/
      - name: Fmt Check
        run: deno fmt --check --ignore=node_modules,.next,public